### ISSUE TITLE
Building error on macOS

### ISSUE THREAD

**Issue by ChenZhao44** [kailaix/AdFem.jl#10]
Hello, I want to try AdFem.jl and I installed it. But when I built the dependent package ADCME.jl, an error occurred.
Here is some environment information:
System: macOS 10.15.7
Julia version: v1.5.2
Error message:
```julia
(@v1.5) pkg> build ADCME
   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building PyCall → `~/.julia/packages/PyCall/BcTLp/deps/build.log`
   Building CMake ─→ `~/.julia/packages/CMake/ULbyn/deps/build.log`
   Building HDF5 ──→ `~/.julia/packages/HDF5/T1b9x/deps/build.log`
   Building FFTW ──→ `~/.julia/packages/FFTW/DMUbN/deps/build.log`
   Building ADCME ─→ `~/.julia/packages/ADCME/fic9z/deps/build.log`
┌ Error: Error building `ADCME`:
│ PREFIX=/Users/chenzhao/.julia/adcme
│ Unpacking payload ...
Extracting : tensorflow-1.15.0-mkl_py37hb249377_0.conda:   0%|          | 0/86 [Extracting : tensorflow-1.15.0-mkl_py37hb249377_0.conda:   1%|          | 1/86 [Extracting : urllib3-1.25.8-py37_0.conda:   1%|          | 1/86 [00:00<00:25,  3                                                                                concurrent.futures.process._RemoteTraceback:
│ '''
│ Traceback (most recent call last):
│   File "concurrent/futures/process.py", line 368, in _queue_management_worker
│   File "multiprocessing/connection.py", line 251, in recv
│ TypeError: __init__() missing 1 required positional argument: 'msg'
│ '''
│
│ The above exception was the direct cause of the following exception:
│
│ Traceback (most recent call last):
│   File "entry_point.py", line 69, in <module>
│   File "concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
│   File "concurrent/futures/_base.py", line 611, in result_iterator
│   File "concurrent/futures/_base.py", line 439, in result
│   File "concurrent/futures/_base.py", line 388, in __get_result
│ concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
│ [1986] Failed to execute script entry_point
│ ┌ Warning: Pkg.installed() is deprecated
│ └ @ Pkg /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:554
│ ┌ Warning: Pkg.installed() is deprecated
│ └ @ Pkg /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:554
│ [ Info: Your Julia version is 1.5.2, current ADCME version is 0.6.2, ADCME dependencies installation path: /Users/chenzhao/.julia/adcme
│ [ Info:  --------------- (1/6) Install Tensorflow Dependencies  ---------------
│ [ Info: Installing miniconda...
│ ERROR: LoadError: LoadError: failed process: Process(`bash Miniconda3-py37_4.8.3-MacOSX-x86_64.sh -f -b -p adcme`, ProcessExited(1)) [1]
│
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at ./process.jl:440
│  [3] run(::Cmd) at ./process.jl:438
│  [4] top-level scope at /Users/chenzhao/.julia/packages/ADCME/fic9z/deps/install_adcme.jl:48
│  [5] include(::String) at ./client.jl:457
│  [6] top-level scope at /Users/chenzhao/.julia/packages/ADCME/fic9z/deps/build.jl:55
│  [7] include(::String) at ./client.jl:457
│  [8] top-level scope at none:5
│ in expression starting at /Users/chenzhao/.julia/packages/ADCME/fic9z/deps/install_adcme.jl:19
│ in expression starting at /Users/chenzhao/.julia/packages/ADCME/fic9z/deps/build.jl:55
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949
```

**Comment by kailaix** [comment]
Could you check if you are able to install Miniconda in the adcme directory? (You may need to remove `/Users/chenzhao/.julia/adcme` if it already exists)

```bash
cd /Users/chenzhao/.julia/
bash Miniconda3-py37_4.8.3-MacOSX-x86_64.sh -f -b -p adcme
```

**Comment by ChenZhao44** [comment]
Thanks @kailaix ! The building of ADCME.jl passed. However, the building of AdFem.jl failed. It seems like there is something wrong with the clang compiler.
```julia
(@v1.5) pkg> build AdFem
   Building HDF5 ──→ `~/.julia/packages/HDF5/T1b9x/deps/build.log`
   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building PyCall → `~/.julia/packages/PyCall/BcTLp/deps/build.log`
   Building CMake ─→ `~/.julia/packages/CMake/ULbyn/deps/build.log`
   Building FFTW ──→ `~/.julia/packages/FFTW/DMUbN/deps/build.log`
   Building ADCME ─→ `~/.julia/packages/ADCME/87dLQ/deps/build.log`
   Building AdFem ─→ `~/.julia/dev/AdFem/deps/build.log`
┌ Error: Error building `AdFem`:
│ WARNING: Method definition size(PyCall.PyObject) in module PyCall at /Users/chenzhao/.julia/packages/PyCall/BcTLp/src/PyCall.jl:809 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/variable.jl:212.
│   ** incremental compilation may be fatally broken for this module **
│
│ WARNING: Method definition length(PyCall.PyObject) in module PyCall at /Users/chenzhao/.julia/packages/PyCall/BcTLp/src/PyCall.jl:808 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/variable.jl:236.
│   ** incremental compilation may be fatally broken for this module **
│
│ WARNING: Method definition lastindex(PyCall.PyObject) in module PyCall at deprecated.jl:70 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/variable.jl:424.
│   ** incremental compilation may be fatally broken for this module **
│
│ WARNING: Method definition *(PyCall.PyObject, PyCall.PyObject) in module PyCall at /Users/chenzhao/.julia/packages/PyCall/BcTLp/src/pyoperators.jl:11 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/ops.jl:102.
│   ** incremental compilation may be fatally broken for this module **
│
│ -- The C compiler identification is unknown
│ -- The CXX compiler identification is unknown
│ -- Check for working C compiler: /Users/chenzhao/.julia/adcme/bin/clang
│ -- Check for working C compiler: /Users/chenzhao/.julia/adcme/bin/clang -- broken
│ CMake Error at /Users/chenzhao/.julia/packages/CMake/ULbyn/deps/downloads/cmake-3.15.3-Darwin-x86_64/CMake.app/Contents/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
│   The C compiler
│
│     "/Users/chenzhao/.julia/adcme/bin/clang"
│
│   is not able to compile a simple test program.
│
│   It fails with the following output:
│
│     Change Dir: /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build/CMakeFiles/CMakeTmp
│
│     Run Build Command(s):/Users/chenzhao/.julia/adcme/bin/ninja cmTC_187c5 && [1/2] Building C object CMakeFiles/cmTC_187c5.dir/testCCompiler.c.o
│     FAILED: CMakeFiles/cmTC_187c5.dir/testCCompiler.c.o
│     /Users/chenzhao/.julia/adcme/bin/clang    -o CMakeFiles/cmTC_187c5.dir/testCCompiler.c.o   -c testCCompiler.c
│     dyld: Library not loaded: @rpath/libLLVM-10.dylib
│       Referenced from: /Users/chenzhao/.julia/adcme/bin/clang
│       Reason: no suitable image found.  Did find:
│     	/Users/chenzhao/.julia/adcme/lib/libLLVM-10.dylib: truncated mach-o error: segment __TEXT extends to 58675200 which is past end of file 11278336
│     	/Users/chenzhao/.julia/adcme/lib/libLLVM-10.dylib: stat() failed with errno=1
│     	/Users/chenzhao/.julia/adcme/bin/../lib/libLLVM-10.dylib: truncated mach-o error: segment __TEXT extends to 58675200 which is past end of file 11278336
│     	/Users/chenzhao/.julia/adcme/bin/../lib/libLLVM-10.dylib: stat() failed with errno=1
│     	/Users/chenzhao/.julia/adcme/bin/../lib/libLLVM-10.dylib: truncated mach-o error: segment __TEXT extends to 58675200 which is past end of file 11278336
│     	/Users/chenzhao/.julia/adcme/bin/../lib/libLLVM-10.dylib: stat() failed with errno=1
│     	/Users/chenzhao/.julia/adcme/lib/libLLVM-10.dylib: truncated mach-o error: segment __TEXT extends to 58675200 which is past end of file 11278336
│     	/Users/chenzhao/.julia/adcme/lib/libLLVM-10.dylib: stat() failed with errno=1
│     ninja: build stopped: subcommand failed.
│
│
│
│
│
│   CMake will not be able to correctly generate this project.
│ Call Stack (most recent call first):
│   CMakeLists.txt:2 (project)
│
│
│ -- Configuring incomplete, errors occurred!
│ See also "/Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build/CMakeFiles/CMakeOutput.log".
│ See also "/Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build/CMakeFiles/CMakeError.log".
│ ninja: error: loading 'build.ninja': No such file or directory
│ ┌ Warning: Cannot load /Users/chenzhao/.julia/packages/ADCME/87dLQ/deps/CustomOps/build/libadcme.dylib. Please recompile the shared library by `ADCME.precompile()` for using custom operators.
│ └ @ ADCME ~/.julia/packages/ADCME/87dLQ/src/ADCME.jl:92
│ [ Info: Copy "/Users/chenzhao/.julia/packages/ADCME/87dLQ/src/../deps/AdeptCMakeLists.txt" to "/Users/chenzhao/.julia/adcme/lib/Adept-2/adept/CMakeLists.txt" ...
│ [ Info: Remove /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build ...
│ [ Info: Make /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build ...
│ [ Info: Change directory into /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build ...
│ [ Info: Cmake ...
│ [ Info: Changed to directory /Users/chenzhao/.julia/adcme/lib/Libraries
│ [ Info: File mfem.zip exists
│ [ Info: File /Users/chenzhao/.julia/adcme/lib/Libraries/mfem-shared-msvc-dev exists
│ [ Info: Changed to directory mfem-shared-msvc-dev/build
│ [ Info: File CMakeCache.txt exists
│ ERROR: LoadError: failed process: Process(setenv(`/Users/chenzhao/.julia/adcme/bin/ninja -j20`,["_CE_M=", "LSCOLORS=Gxfxcxdxbxegedabagacad", "PATH=/Users/chenzhao/.local/bin:/Users/chenzhao/opt/miniconda3/bin:/Users/chenzhao/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin", "HDF5_USE_FILE_LOCKING=FALSE", "LD_LIBRARY_PATH=/Users/chenzhao/.julia/adcme/lib", "ITERM_PROFILE=Default", "USER=chenzhao", "LESS=-R", "CONDA_PROMPT_MODIFIER=", "SHELL=/bin/zsh"  …  "TERM_PROGRAM_VERSION=3.3.12", "ZSH=/Users/chenzhao/.oh-my-zsh", "PWD=/Users/chenzhao/.julia/adcme/bin", "TERM_PROGRAM=iTerm.app", "__KMP_REGISTERED_LIB_8145=0x138d6c168-cafe4507-libomp.dylib", "OPENBLAS_NUM_THREADS=8", "CONDA_PREFIX=/Users/chenzhao/opt/miniconda3", "TERM_SESSION_ID=w1t0p0:F40AA86A-4902-4E35-AE1E-42CD4AFEFB93", "JULIA_LOAD_PATH=@:/var/folders/b5/5jdvvgzn7jx42fnvs0r9p8yc0000gn/T/jl_Vazq89", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
│
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at ./process.jl:440
│  [3] run at ./process.jl:438 [inlined]
│  [4] make() at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/extra.jl:92
│  [5] #282 at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/install.jl:121 [inlined]
│  [6] require_library(::ADCME.var"#282#286", ::String) at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/toolchain.jl:212
│  [7] install_mfem() at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/install.jl:120
│  [8] top-level scope at /Users/chenzhao/.julia/dev/AdFem/deps/build.jl:4
│  [9] include(::String) at ./client.jl:457
│  [10] top-level scope at none:5
│ in expression starting at /Users/chenzhao/.julia/dev/AdFem/deps/build.jl:4
│ Compliation failed
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949
```

**Comment by kailaix** [comment]
It seems like your ADCME is not properly built. How did you solve the ADCME build problem? Installing Miniconda is not the end.

**Comment by ChenZhao44** [comment]
@kailaix I removed the directory `~/.julia/adcme` and run the Miniconda script. Then the building of ADCME passed.

**Comment by kailaix** [comment]
Then your installation is not finished. Since you've installed Miniconda manually, could you finish the rest of the installation also manually:

```julia-repl
julia> cd("~/.julia/packages/ADCME/87dLQ/deps")
julia> include("build.jl")
```

If you encounter any error message, please paste the information here.

**Comment by ChenZhao44** [comment]
After manual installation, it still failed in AdFem.jl.
```julia
(@v1.5) pkg> build AdFem
   Building HDF5 ──→ `~/.julia/packages/HDF5/T1b9x/deps/build.log`
   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building PyCall → `~/.julia/packages/PyCall/BcTLp/deps/build.log`
   Building CMake ─→ `~/.julia/packages/CMake/ULbyn/deps/build.log`
   Building FFTW ──→ `~/.julia/packages/FFTW/DMUbN/deps/build.log`
   Building ADCME ─→ `~/.julia/packages/ADCME/87dLQ/deps/build.log`
   Building AdFem ─→ `~/.julia/dev/AdFem/deps/build.log`
┌ Error: Error building `AdFem`:
│ WARNING: Method definition size(PyCall.PyObject) in module PyCall at /Users/chenzhao/.julia/packages/PyCall/BcTLp/src/PyCall.jl:809 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/variable.jl:212.
│   ** incremental compilation may be fatally broken for this module **
│
│ WARNING: Method definition length(PyCall.PyObject) in module PyCall at /Users/chenzhao/.julia/packages/PyCall/BcTLp/src/PyCall.jl:808 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/variable.jl:236.
│   ** incremental compilation may be fatally broken for this module **
│
│ WARNING: Method definition lastindex(PyCall.PyObject) in module PyCall at deprecated.jl:70 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/variable.jl:424.
│   ** incremental compilation may be fatally broken for this module **
│
│ WARNING: Method definition *(PyCall.PyObject, PyCall.PyObject) in module PyCall at /Users/chenzhao/.julia/packages/PyCall/BcTLp/src/pyoperators.jl:11 overwritten in module ADCME at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/ops.jl:102.
│   ** incremental compilation may be fatally broken for this module **
│
│ -- The C compiler identification is Clang 10.0.1
│ -- The CXX compiler identification is Clang 10.0.1
│ -- Check for working C compiler: /Users/chenzhao/.julia/adcme/bin/clang
│ -- Check for working C compiler: /Users/chenzhao/.julia/adcme/bin/clang -- broken
│ CMake Error at /Users/chenzhao/.julia/packages/CMake/ULbyn/deps/downloads/cmake-3.15.3-Darwin-x86_64/CMake.app/Contents/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
│   The C compiler
│
│     "/Users/chenzhao/.julia/adcme/bin/clang"
│
│   is not able to compile a simple test program.
│
│   It fails with the following output:
│
│     Change Dir: /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build/CMakeFiles/CMakeTmp
│
│     Run Build Command(s):/Users/chenzhao/.julia/adcme/bin/ninja cmTC_9176c && [1/2] Building C object CMakeFiles/cmTC_9176c.dir/testCCompiler.c.o
│     [2/2] Linking C executable cmTC_9176c
│     FAILED: cmTC_9176c
│     : && /Users/chenzhao/.julia/adcme/bin/clang -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_9176c.dir/testCCompiler.c.o  -o cmTC_9176c   && :
│     ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64
│     clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
│     ninja: build stopped: subcommand failed.
│
│
│
│
│
│   CMake will not be able to correctly generate this project.
│ Call Stack (most recent call first):
│   CMakeLists.txt:2 (project)
│
│
│ -- Configuring incomplete, errors occurred!
│ See also "/Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build/CMakeFiles/CMakeOutput.log".
│ See also "/Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build/CMakeFiles/CMakeError.log".
│ ninja: error: loading 'build.ninja': No such file or directory
│ ┌ Warning: Cannot load /Users/chenzhao/.julia/packages/ADCME/87dLQ/deps/CustomOps/build/libadcme.dylib. Please recompile the shared library by `ADCME.precompile()` for using custom operators.
│ └ @ ADCME ~/.julia/packages/ADCME/87dLQ/src/ADCME.jl:92
│ [ Info: Copy "/Users/chenzhao/.julia/packages/ADCME/87dLQ/src/../deps/AdeptCMakeLists.txt" to "/Users/chenzhao/.julia/adcme/lib/Adept-2/adept/CMakeLists.txt" ...
│ [ Info: Remove /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build ...
│ [ Info: Make /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build ...
│ [ Info: Change directory into /Users/chenzhao/.julia/adcme/lib/Adept-2/adept/build ...
│ [ Info: Cmake ...
│ [ Info: Changed to directory /Users/chenzhao/.julia/adcme/lib/Libraries
│ [ Info: File mfem.zip exists
│ [ Info: File /Users/chenzhao/.julia/adcme/lib/Libraries/mfem-shared-msvc-dev exists
│ [ Info: Changed to directory mfem-shared-msvc-dev/build
│ [ Info: File CMakeCache.txt exists
│ ERROR: LoadError: failed process: Process(setenv(`/Users/chenzhao/.julia/adcme/bin/ninja -j20`,["_CE_M=", "LSCOLORS=Gxfxcxdxbxegedabagacad", "PATH=/Users/chenzhao/.local/bin:/Users/chenzhao/opt/miniconda3/bin:/Users/chenzhao/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin", "HDF5_USE_FILE_LOCKING=FALSE", "LD_LIBRARY_PATH=/Users/chenzhao/.julia/adcme/lib", "ITERM_PROFILE=Default", "USER=chenzhao", "LESS=-R", "CONDA_PROMPT_MODIFIER=", "SHELL=/bin/zsh"  …  "TERM_PROGRAM_VERSION=3.3.12", "ZSH=/Users/chenzhao/.oh-my-zsh", "PWD=/Users/chenzhao/.julia", "TERM_PROGRAM=iTerm.app", "__KMP_REGISTERED_LIB_11276=0x11f0dd168-cafeb85a-libomp.dylib", "OPENBLAS_NUM_THREADS=8", "CONDA_PREFIX=/Users/chenzhao/opt/miniconda3", "TERM_SESSION_ID=w1t1p0:1A602A5C-9269-4117-AC7A-6AA1D529064C", "JULIA_LOAD_PATH=@:/var/folders/b5/5jdvvgzn7jx42fnvs0r9p8yc0000gn/T/jl_Dvg9h1", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
│
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at ./process.jl:440
│  [3] run at ./process.jl:438 [inlined]
│  [4] make() at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/extra.jl:92
│  [5] #282 at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/install.jl:121 [inlined]
│  [6] require_library(::ADCME.var"#282#286", ::String) at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/toolchain.jl:212
│  [7] install_mfem() at /Users/chenzhao/.julia/packages/ADCME/87dLQ/src/install.jl:120
│  [8] top-level scope at /Users/chenzhao/.julia/dev/AdFem/deps/build.jl:4
│  [9] include(::String) at ./client.jl:457
│  [10] top-level scope at none:5
│ in expression starting at /Users/chenzhao/.julia/dev/AdFem/deps/build.jl:4
│ Compliation failed
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949

```

**Comment by kailaix** [comment]
What was the output of 
```
julia> include("build.jl")
```
when you try to install manually? Was there any errors?

**Comment by ChenZhao44** [comment]
There was no error when installing manually.
```julia
julia> include("build.jl")
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:554
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:554
[ Info: Your Julia version is 1.5.2, current ADCME version is 0.6.3, ADCME dependencies installation path: /Users/chenzhao/.julia/adcme
[ Info:  --------------- (1/6) Install Tensorflow Dependencies  ---------------
[ Info: Installing miniconda...
PREFIX=/Users/chenzhao/.julia/adcme
Unpacking payload ...
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/chenzhao/.julia/adcme

  added / updated specs:
    - ca-certificates==2020.1.1=0
    - certifi==2020.4.5.1=py37_0
    - cffi==1.14.0=py37hc512035_1
    - chardet==3.0.4=py37_1003
    - conda-package-handling==1.6.1=py37h1de35cc_0
    - conda==4.8.3=py37_0
    - cryptography==2.9.2=py37ha12b0ac_0
    - idna==2.9=py_1
    - libcxx==10.0.0=1
    - libedit==3.1.20181209=hb402a30_0
    - libffi==3.3=h0a44026_1
    - ncurses==6.2=h0a44026_1
    - openssl==1.1.1g=h1de35cc_0
    - pip==20.0.2=py37_3
    - pycosat==0.6.3=py37h1de35cc_0
    - pycparser==2.20=py_0
    - pyopenssl==19.1.0=py37_0
    - pysocks==1.7.1=py37_0
    - python.app==2=py37_10
    - python==3.7.7=hf48f09d_4
    - readline==8.0=h1de35cc_0
    - requests==2.23.0=py37_0
    - ruamel_yaml==0.15.87=py37h1de35cc_0
    - setuptools==46.4.0=py37_0
    - six==1.14.0=py37_0
    - sqlite==3.31.1=h5c1f38d_1
    - tk==8.6.8=ha441bb4_0
    - tqdm==4.46.0=py_0
    - urllib3==1.25.8=py37_0
    - wheel==0.34.2=py37_0
    - xz==5.2.5=h1de35cc_0
    - yaml==0.1.7=hc338f04_2
    - zlib==1.2.11=h1de35cc_3


The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2020.6.2~ --> pkgs/main::ca-certificates-2020.1.1-0
  certifi            conda-forge::certifi-2020.6.20-py37hc~ --> pkgs/main::certifi-2020.4.5.1-py37_0
  conda              conda-forge::conda-4.8.4-py37hc8dfbb8~ --> pkgs/main::conda-4.8.3-py37_0
  openssl            conda-forge::openssl-1.1.1g-haf1e3a3_1 --> pkgs/main::openssl-1.1.1g-h1de35cc_0


Preparing transaction: done
Executing transaction: done
installation finished.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.0

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate base
#
# To deactivate an active environment, use
#
#     $ conda deactivate

[ Info:  --------------- (2/6) Check Python Version  ---------------
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:554
   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building PyCall → `~/.julia/packages/PyCall/BcTLp/deps/build.log`
┌ Info: PyCall Python version: /Users/chenzhao/.julia/adcme/bin/python
└ Conda Python version: /Users/chenzhao/.julia/adcme/bin/python
[ Info:  --------------- (3/6) Looking for TensorFlow Dynamic Libraries ---------------
[ Info:  --------------- (4/6) Preparing Custom Operator Environment ---------------
Requirement already satisfied: matplotlib in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (3.3.2)
Requirement already satisfied: certifi>=2020.06.20 in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from matplotlib) (2020.6.20)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: numpy>=1.15 in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from matplotlib) (1.19.1)
Requirement already satisfied: python-dateutil>=2.1 in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from matplotlib) (8.0.0)
Requirement already satisfied: six in /Users/chenzhao/.julia/adcme/lib/python3.7/site-packages (from cycler>=0.10->matplotlib) (1.14.0)
[ Info:  --------------- (5/6) Skipped: Installing GPU Dependencies  ---------------
[ Info:  --------------- (6/6) Write Dependency Files  ---------------
[ Info:  --------------- Finished: /Users/chenzhao/.julia/packages/ADCME/87dLQ/deps/deps.jl  ---------------
```

**Comment by Ricahrd-Li** [comment]
Hi ChenZhao,
may I ask how much time does the step "(3/6) Looking for TensorFlow Dynamic Libraries " take?
For me this step seems to be stuck and has already taken 30+ minutes. 
Thx.
@ChenZhao44
